const karten = {
    1: "Weli",
    2: "Schell Sieben",
    3: "Schell Acht",
    4: "Schell Neun",
    5: "Schell Zehn",
    6: "Schell Unter",
    7: "Schell Ober",
    8: "Schell König",
    9: "Schell Ass",
    10: "Herz Sieben",
    11: "Herz Acht",
    12: "Herz Neun",
    13: "Herz Zehn",
    14: "Herz Unter",
    15: "Herz Ober",
    16: "Herz König",
    17: "Herz Ass",
    18: "Eichel Sieben",
    19: "Eichel Acht",
    20: "Eichel Neun",
    21: "Eichel Zehn",
    22: "Eichel Unter",
    23: "Eichel Ober",
    24: "Eichel König",
    25: "Eichel Ass",
    26: "Laub Sieben",
    27: "Laub Acht",
    28: "Laub Neun",
    29: "Laub Zehn",
    30: "Laub Unter",
    31: "Laub Ober",
    32: "Laub König",
    33: "Laub Ass",
  };

  let kardNums = [.karten.keys()]
  console.log(kardNums)